### ISSUE TITLE
Idee per la mappa

### ISSUE THREAD

**Issue by matteociccaglione** [kobero98/TravelBook#20]
Ragazzi vi piacerebbe una cosa del genere per la mappa:
Inseriamo nel popup che si apre su ogni marker una specie di bottone (o un hyperlink) del tipo "Vedi altri viaggi in questo posto e nelle vicinanze"(magari una frase più carina) e se ci clicca l'utente viene portato alla pagina di search dove tra i risultati avrà i viaggi che sono andati in quel posto o nella stessa città... secondo voi si può fare con il nostro db? 
Oppure un'altra idea sulla stessa linea era di inserire un bottone "Vedi le descrizioni di altri utenti" e apriva a destra un Pane dove dentro ci stavano le descrizioni di altri utenti ma sinceramente mi piace di meno.
Ditemi se vi piace se è utile o se fa cagare hahahaha.
Poi un'altra cosa è io non mi sono proprio interessato del meteo sinceramente mi sono dimenticato... voi che dite è proprio necessario? Se serve vedo di trovare un modo per mettercelo

**Comment by Sara-DaCanal** [comment]
Per il meteo credo lo abbiamo dimenticato un po' tutti, per me si può dimenticare punto, dovremmo modificare tutte le pagine
Per quanto riguarda l'altra idea, è molto figo, però sinceramente manca molto ancora al progetto, mancano tutti i test, la documentazione è da rivedere e non credo sia un lavoro breve, se non vogliamo toglierlo manca anche tutta la parte di organized trip... io taglierei corto sull'aggiungere altre funzionalità e mi concentrerei su fare bene questo che stiamo facendo, perché sono d'accordo che programmare è più divertente che fargli i diagrammi i test sonarcloud travis e via dicendo ma i prof valutano che ci sia tutta quella roba e non che la nostra app abbia un milione di funzionalità

**Comment by matteociccaglione** [comment]
Ok va bene io organized trip lo davo già per abbandonato in realtà hahaha

**Comment by Sara-DaCanal** [comment]
si anche io un po', allora va tolto dall'explore il collegamento, però significa che ci sta ancora più lavoro a rifare i diagrammi
